GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Jhon Doe",
    "email": "john@gmail.com",
    "gender": "Male"
}

###
PATCH  http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "M Fikri",
    "email": "fikri@gmail.com",
    "gender": "Female"
}

###
DELETE http://localhost:5000/users/2